apiVersion: federation.maistra.io/v1
kind: ExportedServiceSet
metadata:
  name: mesh2
  namespace: mesh1-system
spec:
  exportRules:
  - type: NameSelector
    nameSelector:
      namespace: mesh1-bookinfo
      name: ratings
      alias:
        namespace: bookinfo
        name: ratings
  - type: NameSelector
    nameSelector:
      namespace: mesh1-bookinfo
      name: mongodb
      alias:
        namespace: bookinfo
        name: mongodb
