apiVersion: release-notes/v2
kind: bug-fix
area: installation

issue:
  - 41159

releaseNotes:
  - |
    **Fixed** an issue `istio-operator` can not create cni properly when `cni.resourceQuotas` is enabled.
