apiVersion: release-notes/v2
kind: bug-fix 
area: traffic-management

issue:
  - 40394
  - 41462 

docs:
  - '[Optimized Design] https://docs.google.com/document/d/15LP2XHpQ71ODkjCVItGacPgzcn19fsVhyE7ruMGXDyU/'
  - '[Original Design] https://docs.google.com/document/d/1oT6pmRhOw7AtsldU0-HbfA0zA26j9LYiBD_eepeErsQ/'

releaseNotes:
- |
  **Fixed** fixed bug of Istio cannot be deployed on IPv6-first DS clusters for Dual Stack support in Istio. 
