apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
- 43435
releaseNotes:
- |
  **Fixed** an issue where `EnvoyFilter` for `Cluster.ConnectTimeout` was affecting unrelated `Clusters`.
