apiVersion: release-notes/v2
kind: feature
area: istioctl
issue:
  - 43842
releaseNotes:
  - |
    **Added** `--output-dir` flag to specify the output directory for the `bug-report` command's generated archive file.
