
apiVersion: release-notes/v2
kind: bug-fix
area: installation
issue:
  - 42485

releaseNotes:
- |
  **Fixed** SELinux issue on CentOS9/RHEL9 where iptables-restore isn't allowed
  to open files in /tmp. Rules passed to iptables-restore are no longer written
  to a file, but are passed via stdin.
