apiVersion: release-notes/v2
kind: bug-fix
area: istioctl
releaseNotes:
- |
  **Fixed** an issue where xDS `proxy-status` was showing inaccurate Istio version. Note: please ensure that both istioctl and istiod are upgraded for this fix to work.
