apiVersion: release-notes/v2
kind: bug-fix
area: istioctl
releaseNotes:
- |
  **Fixed** an issue where Ztunnel pods could be compared to Envoy configs in `istioctl proxy-status` and `istioctl x proxy-status`. They are now excluded from the comparison.
