apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
- |
  **Removed** the following experimental `istioctl` commands: `create-remote-secret` and `remote-clusters`.
  They have been moved to the top level `istioctl` command.
