apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
- |
  **Added** `--output-threshold` flag in `istioctl experimental precheck` to control message output threshold.
  Now the default threshold is `warning`, which replaces the previous behavior of `info`.
