apiVersion: release-notes/v2
kind: bug-fix
area: installation
issue:
- 46859
releaseNotes:
- |
  **Fixed** an issue where the installation process was failing due to failed verification of the `NetworkAttachmentDefinition` resource.
