apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
- |
  **Added** support for setting loggers' levels of istio-proxy in `istioctl proxy-config log` command with `--level <level>` or `--level level=<level>`.
