apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
  - |
    **Improved** pilot-agent will return the return of http probe body from the original probe API setting in the container as well as statuscode.