apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
  - |
    **Fixed** an issue that `convertToEnvoyFilterWrapper` still returns the invalid patch and may cause NPE when apply it.
