apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
- |
  **Added** namespace filtering to `istioctl pc workload` using the `--workloads-namespace` flag, to display workloads in a specific namespace.
