apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
releaseNotes:
  - |
    **Fixed** an bug when specify a uri regex `.*` match within a vs http route, it does not short cicuirt the other http routes behind.
