apiVersion: release-notes/v2
kind: feature
area: installation
issue: []
releaseNotes:
- |
  **Added** affinity field to Istiod Deployment. This field is used to control the scheduling of Istiod pods.
