apiVersion: release-notes/v2
kind: feature
area: istioctl
releaseNotes:
  - |
    **Improved** the `istioctl analyze` to output mismatched proxy image messages as IST0158 on namespace level instead of IST0105 on pod level, which is more succinct.
