apiVersion: release-notes/v2
kind: feature
area: security
releaseNotes:
  - |
    **Added** Certificate Revocation List(CRL) support for peer certificate validation based on file paths specified in 
    ClientTLSSettings in destination rule for Sidecars and in ServerTLSSettings in Gateway for Gateways.