apiVersion: release-notes/v2
kind: bug-fix
area: installation
releaseNotes:
  - |
    **Fixed** an issue where installing with Stackdriver and having custom configs would lead to Stackdriver not being enabled.