apiVersion: release-notes/v2
kind: feature
area: telemetry
issue: []
releaseNotes:
  - |
    **Added** HTTP metadata exchange filter to support a fallback to xDS workload metadata discovery in addition to the metadata HTTP headers. The discovery method is off by default.
