apiVersion: release-notes/v2
kind: bug-fix
area: security
issue:
  - https://github.com/istio/istio/issues/43785
releaseNotes:
  - |
    **Fixed** an issue where RBAC updates were not sent to older proxies after upgrading istiod to 1.17.
