apiVersion: release-notes/v2
kind: feature
area: installation
releaseNotes:
  - |
    **Removed** obsolete manifests from the `base` Helm chart. See Upgrade Notes for more information.
upgradeNotes:
  - title: "`base` Helm Chart removals"
    content: |
      A number of configurations previously present in the the `base` Helm chart were *copied* to the `istiod` chart in a previous releases.

      In this release, the duplicated configurations are fully removed from the `base` chart.

      Below shows a mapping of old configuration to new configuration:

      | Old                                     | New                                     |
      | --------------------------------------- | --------------------------------------- |
      | `ClusterRole istiod`                    | `ClusterRole istiod-clusterrole`        |
      | `ClusterRole istiod-reader`             | `ClusterRole istio-reader-clusterrole`  |
      | `ClusterRoleBinding istiod`             | `ClusterRoleBinding istiod-clusterrole` |
      | `Role istiod`                           | `Role istiod`                           |
      | `RoleBinding istiod`                    | `RoleBinding istiod`                    |
      | `ServiceAccount istiod-service-account` | `ServiceAccount istiod`                 |

      Note: most resources have a suffix automatically added in addition.
      In the old chart, this was `-{{ .Values.global.istioNamespace }}`.
      In the new chart it is `{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}` for namespace scoped resources, and `{{- if not (eq .Values.revision "")}}-{{ .Values.revision }}{{- end }}-{{ .Release.Namespace }}` for cluster scoped resources.
