apiVersion: release-notes/v2
kind: feature
area: traffic-management
releaseNotes:
- |
  **Added** support for a max concurrent streams setting in the DestinationRule's HTTP traffic policy for HTTP2 conections.
