apiVersion: release-notes/v2
kind: feature
area: installation
issue:
- 49290
releaseNotes:
- |
  **Improved** helm value field names to configure whether an existing CNI install
   will be used. Instead of values.istio_cni the enablement fields will be in
   values.pilot.cni as istiod is the affected component.
   That is clearer than having values.cni for install config and values.istio_cni
   for enablement in istiod. The old values.istio_cni fields will still be supported
   for at least two releases.
