apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
- https://github.com/istio/istio/pull/43152
releaseNotes:
  - |
    **Fixed** an issue where sidecars do not proxy DNS properly for a hostname backed by multiple services.
