apiVersion: release-notes/v2
kind: feature
area: traffic-management

releaseNotes:
  - |
    **Added** a new TLS mode 'OPTIONAL_MUTUAL' in ServerTLSSettings of Gateway that will validate client certificate if presented but not mandate it.