apiVersion: release-notes/v2
kind: feature
area: installation
releaseNotes:
- |
  **Improved** the `meshConfig.defaultConfig.proxyMetadata` field to do a deep merge when overridden, rather than replacing all values.
