apiVersion: release-notes/v2
kind: feature
area: installation
docs:
- 'https://istio.io/latest/docs/setup/platform-setup/openshift/'
releaseNotes:
- |
    **Improved** Usage on OpenShift clusters is simplified by removing the need of granting the `anyuid` SCC privilege to Istio and applications.
