apiVersion: release-notes/v2
kind: bug-fix
area: traffic-management
issue:
- https://github.com/istio/istio/issues/49878
releaseNotes:
- |
  **Fixed** an issue where updating a ServiceEntry's TargetPort does not trigger an xDS push.
