apiVersion: release-notes/v2
kind: feature
area: telemetry
releaseNotes:
- |
  **Fixed** an issue where `Telemetry` would not be fully disabled unless `match.metric=ALL_METRICS` was explicitly specified; matching all metrics is now correctly considered as the default.
