apiVersion: release-notes/v2
kind: bug-fix
area: istioctl
releaseNotes:
  - |
    **Fixed** `istioctl experimental  wait` has undecipherable message when PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING is not enabled.
