FROM quay.io/centos/centos:stream8 as centos

ENV container="oci"
ENV ISTIO_VERSION="${ISTIO_VERSION}"

RUN dnf update -y && dnf clean all

ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/istio-cni /opt/cni/bin/istio-cni
COPY ${TARGETARCH:-amd64}/install-cni /usr/local/bin/install-cni

# Copy over the Taint binary
COPY ${TARGETARCH:-amd64}/istio-cni-taint /opt/local/bin/istio-cni-taint

ENV PATH=$PATH:/opt/cni/bin
WORKDIR /opt/cni/bin
CMD ["/usr/local/bin/install-cni"]
