apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-application
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ambient-cluster
    namespace: ambient
  source:
    path: application
    repoURL: '{repo-placeholder}'
    targetRevision: HEAD
    directory:
      exclude: application.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true