apiVersion: maistra.io/v1
kind: MeshFederation
metadata:
  name: mesh1
  namespace: mesh2-system
spec:
  remote:
    addresses:
    - mesh2-ingress.mesh1-system.svc.cluster.local
  gateways:
    ingress:
      name: mesh1-ingress
    egress:
      name: mesh1-egress
  security:
    trustDomain: mesh1.local
    clientID: mesh1.local/ns/mesh1-system/sa/mesh2-egress-service-account
    # same as default, if certificateChain is omitted
    certificateChain:
      kind: ConfigMap
      name: mesh1-ca-root-cert
