/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "istio.io/istio/pkg/servicemesh/apis/servicemesh/v1"
	scheme "istio.io/istio/pkg/servicemesh/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceMeshMemberRollsGetter has a method to return a ServiceMeshMemberRollInterface.
// A group's client should implement this interface.
type ServiceMeshMemberRollsGetter interface {
	ServiceMeshMemberRolls(namespace string) ServiceMeshMemberRollInterface
}

// ServiceMeshMemberRollInterface has methods to work with ServiceMeshMemberRoll resources.
type ServiceMeshMemberRollInterface interface {
	Create(*v1.ServiceMeshMemberRoll) (*v1.ServiceMeshMemberRoll, error)
	Update(*v1.ServiceMeshMemberRoll) (*v1.ServiceMeshMemberRoll, error)
	UpdateStatus(*v1.ServiceMeshMemberRoll) (*v1.ServiceMeshMemberRoll, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.ServiceMeshMemberRoll, error)
	List(opts metav1.ListOptions) (*v1.ServiceMeshMemberRollList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceMeshMemberRoll, err error)
	ServiceMeshMemberRollExpansion
}

// serviceMeshMemberRolls implements ServiceMeshMemberRollInterface
type serviceMeshMemberRolls struct {
	client rest.Interface
	ns     string
}

// newServiceMeshMemberRolls returns a ServiceMeshMemberRolls
func newServiceMeshMemberRolls(c *MaistraV1Client, namespace string) *serviceMeshMemberRolls {
	return &serviceMeshMemberRolls{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceMeshMemberRoll, and returns the corresponding serviceMeshMemberRoll object, and an error if there is any.
func (c *serviceMeshMemberRolls) Get(name string, options metav1.GetOptions) (result *v1.ServiceMeshMemberRoll, err error) {
	result = &v1.ServiceMeshMemberRoll{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceMeshMemberRolls that match those selectors.
func (c *serviceMeshMemberRolls) List(opts metav1.ListOptions) (result *v1.ServiceMeshMemberRollList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ServiceMeshMemberRollList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceMeshMemberRolls.
func (c *serviceMeshMemberRolls) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a serviceMeshMemberRoll and creates it.  Returns the server's representation of the serviceMeshMemberRoll, and an error, if there is any.
func (c *serviceMeshMemberRolls) Create(serviceMeshMemberRoll *v1.ServiceMeshMemberRoll) (result *v1.ServiceMeshMemberRoll, err error) {
	result = &v1.ServiceMeshMemberRoll{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		Body(serviceMeshMemberRoll).
		Do().
		Into(result)
	return
}

// Update takes the representation of a serviceMeshMemberRoll and updates it. Returns the server's representation of the serviceMeshMemberRoll, and an error, if there is any.
func (c *serviceMeshMemberRolls) Update(serviceMeshMemberRoll *v1.ServiceMeshMemberRoll) (result *v1.ServiceMeshMemberRoll, err error) {
	result = &v1.ServiceMeshMemberRoll{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		Name(serviceMeshMemberRoll.Name).
		Body(serviceMeshMemberRoll).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *serviceMeshMemberRolls) UpdateStatus(serviceMeshMemberRoll *v1.ServiceMeshMemberRoll) (result *v1.ServiceMeshMemberRoll, err error) {
	result = &v1.ServiceMeshMemberRoll{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		Name(serviceMeshMemberRoll.Name).
		SubResource("status").
		Body(serviceMeshMemberRoll).
		Do().
		Into(result)
	return
}

// Delete takes name of the serviceMeshMemberRoll and deletes it. Returns an error if one occurs.
func (c *serviceMeshMemberRolls) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceMeshMemberRolls) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched serviceMeshMemberRoll.
func (c *serviceMeshMemberRolls) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ServiceMeshMemberRoll, err error) {
	result = &v1.ServiceMeshMemberRoll{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicemeshmemberrolls").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
