/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "istio.io/istio/pkg/servicemesh/apis/servicemesh/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ServiceMeshMemberRollLister helps list ServiceMeshMemberRolls.
type ServiceMeshMemberRollLister interface {
	// List lists all ServiceMeshMemberRolls in the indexer.
	List(selector labels.Selector) (ret []*v1.ServiceMeshMemberRoll, err error)
	// ServiceMeshMemberRolls returns an object that can list and get ServiceMeshMemberRolls.
	ServiceMeshMemberRolls(namespace string) ServiceMeshMemberRollNamespaceLister
	ServiceMeshMemberRollListerExpansion
}

// serviceMeshMemberRollLister implements the ServiceMeshMemberRollLister interface.
type serviceMeshMemberRollLister struct {
	indexer cache.Indexer
}

// NewServiceMeshMemberRollLister returns a new ServiceMeshMemberRollLister.
func NewServiceMeshMemberRollLister(indexer cache.Indexer) ServiceMeshMemberRollLister {
	return &serviceMeshMemberRollLister{indexer: indexer}
}

// List lists all ServiceMeshMemberRolls in the indexer.
func (s *serviceMeshMemberRollLister) List(selector labels.Selector) (ret []*v1.ServiceMeshMemberRoll, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ServiceMeshMemberRoll))
	})
	return ret, err
}

// ServiceMeshMemberRolls returns an object that can list and get ServiceMeshMemberRolls.
func (s *serviceMeshMemberRollLister) ServiceMeshMemberRolls(namespace string) ServiceMeshMemberRollNamespaceLister {
	return serviceMeshMemberRollNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ServiceMeshMemberRollNamespaceLister helps list and get ServiceMeshMemberRolls.
type ServiceMeshMemberRollNamespaceLister interface {
	// List lists all ServiceMeshMemberRolls in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.ServiceMeshMemberRoll, err error)
	// Get retrieves the ServiceMeshMemberRoll from the indexer for a given namespace and name.
	Get(name string) (*v1.ServiceMeshMemberRoll, error)
	ServiceMeshMemberRollNamespaceListerExpansion
}

// serviceMeshMemberRollNamespaceLister implements the ServiceMeshMemberRollNamespaceLister
// interface.
type serviceMeshMemberRollNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ServiceMeshMemberRolls in the indexer for a given namespace.
func (s serviceMeshMemberRollNamespaceLister) List(selector labels.Selector) (ret []*v1.ServiceMeshMemberRoll, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.ServiceMeshMemberRoll))
	})
	return ret, err
}

// Get retrieves the ServiceMeshMemberRoll from the indexer for a given namespace and name.
func (s serviceMeshMemberRollNamespaceLister) Get(name string) (*v1.ServiceMeshMemberRoll, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("servicemeshmemberroll"), name)
	}
	return obj.(*v1.ServiceMeshMemberRoll), nil
}
